steps:
- name: 'ubuntu'
  args: ['bash', './myscript.sh']
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'BNAME=$BRANCH_NAME'
  - 'OWNER=$REPO_OWNER'
  - 'BRANCH=$HEAD_BRANCH'
