steps:
- name: 'ubuntu'
  args: ['bash', './myscript.sh']
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT=$PROJECT_ID'
  - 'REV=$REVISION_ID'
  - 'BASE=$_BASE_BRANCH'
  - 'OWNER=$_REPO_OWNER'
  - 'BRANCH=$_HEAD_BRANCH'
